version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unused
    - usetesting

formatters:
  enable:
    - gofmt
